version: "3.8"
services:
  api:
    build:
      context: .
    environment:
      DB_CONNECTIONSTRING: "User ID=postgres;Password=1Secure*Password1;Server=postgres;Port=5432;Database=Overflow.Db;Integrated Security=true;Pooling=true;"
    ports:
      - 5000:80
    networks:
      - stackoverflow-network
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=1Secure*Password1
    networks: 
      - stackoverflow-network
    volumes:
      - postgres-data:/var/opt/postgres
      
networks:
  stackoverflow-network:
    driver: bridge

volumes:
  postgres-data: 