version: "3.8"
services:
  api:
    environment:
      DB_CONNECTIONSTRING: "Server=mssql;Database=PrynSpec;User=SA;Password=Senha@1234"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - 5000:80
    networks:
      - stackoverflow-network
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Senha@1234"
    networks: 
      - stackoverflow-network
    volumes:
      - mssql-data:/var/opt/mssql
      
networks:
  stackoverflow-network:
    driver: bridge

volumes:
  mssql-data: 